[Variables]

; ========== 基本设置 ==========
Language=English
Location=SPXX0050
Unit=m
Format=H
ScrollMouseIncrement=0.02

; ========== 显隐设置（1=显示，0=隐藏） ==========
Hidden=1
Hidden2=1
Hidden3=0
Hidden4=1
Hidden5=0
Hidden6=1
Hidden7=1
Hidden8=1
Hidden9=1
Hidden10=1

; ========== 播放器相关 ==========
Player=AIMP  ; 另一个皮肤使用 WMP，如需改用可更换
PlayerFontSize=1

; ========== 启动器（Launcher）相关 ==========
LauncherScale=1.2
LauncherScale2=1.2
LauncherColor1=82,82,82
LauncherColor2=0,0,0
LauncherColor3=255,255,255
LauncherColor4=255,255,255

; ========== 字体颜色 ==========
FontColor=0,0,0
FontColor2=255,132,0
FontColor3=0,157,255
FontColor4=120,149,196
FontColor5=255,255,255
FontColor6=255,255,255
FontColor7=255,255,255
FontColor8=217,98,100
FontColor9=0,0,0
FontColor10=255,0,0
FontColor11=235,59,59

TextColor=135,206,250
TextColor1=0,0,0
TextColor2=118,170,207
TextColor3=255,255,255


; ========== 颜色设定 ==========
Color1=29,28,31
Color2=253,254,60
Color3=0,0,0
Black_1=000000
Black_2=0,0,0,128
White=ffffff
Red=255,2,2
Yellow=255,2,2
Grey=1D1C1F

; ========== 可视化器 ==========
VisualizerColor1=200,205,230
VisualizerColor2=219,55,55
VisualizerScale=0.15
VisualizerScale2=2

; ========== 缩放比例 ==========
ClockScale=1.1
QuotesScale=0.6
LinkScale=1
VolumeScale=0.8
SystemScale=0.2

; ========== 尺寸与进度条 ==========
JumpHeight=200
Width=2
Height=100
ProgressBarWidth=362
ProgressBarHeight=1

; ========== 单位换算或系统显示类型 ==========
SystemSize=0,1
