general:
  layout_engine: bsp
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

cursor_jump:
  enabled: true
  trigger: monitor_focus
  hide_method: cloak

show_all_in_taskbar: false

gaps:
  scale_with_dpi: false
  inner_gap: 0px
  outer_gap:
    top: 0px
    right: 0px
    bottom: 0px
    left: 0px

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#8dbcff"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: square
    transparency:
      enabled: false
      opacity: 95%
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: square
    transparency:
      enabled: false
      opacity: 0%

window_behavior:
  initial_state: tiling

state_defaults:
  floating:
    centered: true
    shown_on_top: false
  fullscreen:
    maximized: false
    shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      - window_title:
          regex: "\\[Pp]icture.in.\\[Pp]icture"
        window_class:
          regex: "Chrome_WidgetWin_1|MozillaDialogClass"
      - window_process:
          equals: "PowerToys"
        window_class:
          regex: "HwndWrapper\\$PowerToys\\.PowerAccent.*?$"
      - window_process:
          equals: "PowerToys"
        window_title:
          regex: ".*? - Peek"
      - window_process:
          equals: "Lively"
        window_class:
          regex: "HwndWrapper"
      - window_process:
          regex: "ApplicationFrameHost|ShellExperienceHost|SystemSettings|RuntimeBroker"
      - window_class:
          regex: "MultitaskingViewFrame|PopupHost|HwndWrapper"
  - commands: ["set-floating --centered"]
    match:
      - window_process: { equals: "QQ" }
      - window_process: { equals: "Typora" }

binding_modes:
  - name: resize
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Focus movement
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  # Move window
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Resize (direct)
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]

  # Resize mode
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  # Layout & state toggles
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Window control
  - commands: ["close"]
    bindings: ["alt+shift+q"]
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

  # Shell / launcher
  - commands: ["shell-exec cmd"]
    bindings: ["alt+enter"]

  # Workspace switching
  - commands: ["focus --next-active-workspace"]
    bindings: ["alt+s"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["alt+a"]
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Workspace numbers
  - bindings: ["alt+1"]
    commands: ["focus --workspace 1"]
  - bindings: ["alt+2"]
    commands: ["focus --workspace 2"]
  - bindings: ["alt+3"]
    commands: ["focus --workspace 3"]
  - bindings: ["alt+4"]
    commands: ["focus --workspace 4"]
  - bindings: ["alt+5"]
    commands: ["focus --workspace 5"]
  - bindings: ["alt+6"]
    commands: ["focus --workspace 6"]
  - bindings: ["alt+7"]
    commands: ["focus --workspace 7"]
  - bindings: ["alt+8"]
    commands: ["focus --workspace 8"]
  - bindings: ["alt+9"]
    commands: ["focus --workspace 9"]

  # Move to workspace and switch
  - bindings: ["alt+shift+1"]
    commands: ["move --workspace 1", "focus --workspace 1"]
  - bindings: ["alt+shift+2"]
    commands: ["move --workspace 2", "focus --workspace 2"]
  - bindings: ["alt+shift+3"]
    commands: ["move --workspace 3", "focus --workspace 3"]
  - bindings: ["alt+shift+4"]
    commands: ["move --workspace 4", "focus --workspace 4"]
  - bindings: ["alt+shift+5"]
    commands: ["move --workspace 5", "focus --workspace 5"]
  - bindings: ["alt+shift+6"]
    commands: ["move --workspace 6", "focus --workspace 6"]
  - bindings: ["alt+shift+7"]
    commands: ["move --workspace 7", "focus --workspace 7"]
  - bindings: ["alt+shift+8"]
    commands: ["move --workspace 8", "focus --workspace 8"]
  - bindings: ["alt+shift+9"]
    commands: ["move --workspace 9", "focus --workspace 9"]

  # Move workspace in direction
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+shift+d"]
  - commands: ["move-workspace --direction down"]